baseURL = "https://gaelreyrol.dev"
title = "Gaël Reyrol"
theme = "coder"
languageCode = "fr"
defaultcontentlanguage = "fr"
publishDir = "docs"

paginate = 20
canonifyurls = true
enableEmoji = true

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-82402577-1"
disqusShortname = "gaelreyrol"

[privacy]
    [privacy.googleAnalytics]
        anonymizeIP = true
        respectDoNotTrack = true
        useSessionStorage = true

    [privacy.twitter]
        enableDNT = true
        simple = true

[params]
    author = "Gaël Reyrol"
    info = "Développeur Fullstack, DevOps & Maker"
    description = "Blog personnel de Gaël Reyrol, développeur et maker, caennais"
    keywords = "blog,personnel,développeur,maker,caen"
    avatarurl = "images/avatar.png"

    footercontent = "Théoriquement, ça fonctionne."

    hideCredits = false
    hideCopyright = false

    custom_css = []

    rtl = false

    langseparator = "|"

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/GaelReyrol"
    icon = "fab fa-github fa-2x"
    rel = "me"
    target = "_blank"
[[params.social]]
    name = "Gitlab"
    weight = 2
    url = "https://gitlab.com/GaelReyrol"
    icon = "fab fa-gitlab fa-2x"
    rel = "me"
    target = "_blank"
[[params.social]]
    name = "Twitter"
    weight = 3
    url = "https://twitter.com/GaelReyrol"
    icon = "fab fa-twitter fa-2x"
    rel = "me"
    target = "_blank"
[[params.social]]
    name = "LinkedIn"
    weight = 4
    url = "https://linkedin.com/in/gaelreyrol"
    icon = "fab fa-linkedin fa-2x"
    rel = "me"
    target = "_blank"
[[params.social]]
    name = "Keybase"
    weight = 5
    url = "https://keybase.io/zevran"
    icon = "fab fa-keybase fa-2x"
    rel = "me"
    target = "_blank"
[[params.social]]
    name = "Brown Bag Lunch"
    weight = 6
    url = "http://www.brownbaglunch.fr/baggers.html#gael-reyrol"
    icon = "fab fa-utensils fa-2x"
    rel = "me"
    target = "_blank"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "À propos"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Projets"
    weight = 3
    url = "/projects/"
[[menu.main]]
    name = "Services"
    weight = 4
    url = "/services/"
